language: android

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.gradle

before_install:
# Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > "$ANDROID_HOME/licenses/android-sdk-license"
- echo d56f5187479451eabf01fb78af6dfcb131a6481e >> "$ANDROID_HOME/licenses/android-sdk-license"

after_success:
- .buildscript/deploy-snapshot.sh

env:
  global:
  - secure: WOOj0q1C2RvcERzEVg9rV8ST7MiMHi6AcjjWERUSetLX9BJW/gMkoIE3FJ3ikf6EDw2/aGlUI7W2WIl+7yv7ypcfJFq+Q50T0r9ffz+4T99ucpoSfT84LqHq7I8maqCgwmRABB8QENghumEVwHu3m63dfvExgehXxzeww996igbam1oE1m1V+HO4ENFFduWGsSFJ0DkLjg1yc9+ok7rr62Afjdn1vKcJ21MyZi7RnYjjQm4UiBG8tP/6efFMrLyJqEZ8X3p161TbkmwWvJGbxk62HTntGUjIlBFyuT/ofi2AAV0PiYhOxNYpZ3PYYxoTAlGnZ5wSeQX24WVd1kjPMGC3bT4dCBE021nAyAAFjKsdm+9ukXNFVJQZvN4LU3Vd0Dwoc9f8J7qM7QaL0vHDajhVV5mQl9ennpAV+K9KdPnOqUbwipD9vgy3BwQKBAPuxnFMEm1EtxU5P5clSdXpV4E+sPQW/La/fF3otcaaObKwhrBxaYoQoau5ZfMQuSuUsqhvZhLiUqDPcvCa3kYspZueSq58hIGwQEkguTp5DO6CPY2RUcf7XApkWhmhXArU1eqX5k4V1FbCCt0HqU9NI9C/d4OEUQxEedCd6ivKNI5wG8/co+H/fvbalShaB8dyOjAt/W3RlP3RMwNuH3fTioJocb0F1KCNGQ7hNOfZ22o=
  - secure: bMt5UWmOjJKj3ILhJOwJOa2iSxQdleeSA7jXKLe5qqsaMpOp670t5ObrRlgidfVMOHDgT5VfWiDBZeAiXo5bekXDr866ThCo+LlmQ63VlZdsqQYXIILi3U9jilTZu0q4EY9FDsOiDLtjpJ8UtRuSLngrn3BE720FYrdNZkWQCb0/OfsD4TaFf8Rv14ttHEC0cxuQ2fNwkkPrNbQjjcNjuXzZKmikt/K4WdtXgLslGExNmyDv13xa8bXjlYyP9gYQ0E5XwNtNJHry/iju2gAY3yHaCbctN6/0ZiGSZZJGoht7X22BFMAmtufqzkw/ss0/kRQkwy7Vzrv9r7r6z2RAlsc9vWbsRDCOvsHWL/2W0or4uzzOpfMpAx4wzjiRInkxEw0V/O619464BAJ2J+tXSeE3tfP9RoaKLwF68t+ULb++XdQoD8EcEzorZ+Pg9fk/a0dJ4awZutvYRto/YKKiFJOaCUzAFOj7qGxBUEWe7TTL63O4GwWlEhL+k/9BXKBykxfk6moWrtgIjaiwIZiMqVW63Y4qIyoaePn8nYMW6WkNsipK15ObcWAO/s4Y5ask5/Hh3bhVACJwkWLxwNw3jjdv9O4S9P695KJbsrxEzojVPF6PTXaeuhedp9uEPWD0r61VcX5TuvDoh+vJxTueoYw8iEcI8J5JlNz2B+dkbXQ=
